import Head from "next/head";
import { Header } from "src/components/Header";
import { PostList } from "src/components/PostList";

const Posts = () => {
  return (
    <div>
      <Head>
        <title>Index Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <PostList />
    </div>
  );
};

export default Posts;
