import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { Header } from "src/components/Header";
import styles from "src/styles/Home.module.css";

const Home = (props) => {
  const [posts, setPosts] = useState([]);
  const getPosts = useCallback(async () => {
    const rest = await fetch("https://jsonplaceholder.typicode.com/posts");
    const json = await rest.json();
    setPosts(json);
    console.log(json);
  }, []);

  useEffect(() => {
    getPosts();
  }, [getPosts]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Index Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {posts.length > 0 ? (
        <ol>
          {posts.map((item) => {
            return <li key={item.id}>{item.title}</li>;
          })}
        </ol>
      ) : null}
    </div>
  );
};

export default Home;
