import Head from "next/head";
import { useRouter } from "next/router";
import { CommentsByPostsId } from "src/components/Comments/CommentsByPostld";
import { UserByUSerId } from "src/components/User/UserByUserId";
import { fetcher } from "src/utils/fetcher";
import useSWR from "swr";

export const Post = () => {
  const router = useRouter();
  const { data, error } = useSWR(
    router.query.id
      ? `https://jsonplaceholder.typicode.com/posts/${router.query.id}`
      : null,
    fetcher
  );
  if (error) {
    return <div>{error.message}</div>;
  }

  return (
    <div>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>{data?.title}</h1>
      <p>{data?.body}</p>
      <UserByUSerId id={data?.userId} />
      <CommentsByPostsId id={data?.id} />
    </div>
  );
};
